baseURL = "https://jgoguen.ca/"
languageCode = "en-ca"
defaultcontentlanguage = "en"
title = "Heap Overrun"
theme = "coder"

canonifyurls = true

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

enableGitInfo = true

[frontmatter]
	date = ['date', 'publishDate', 'lastmod']
	expiryDate = ['expiryDate']
	lastmod = [':git', 'lastmod', 'date', 'publishDate']
	publishDate = ['publishDate', 'date']

[permalinks]
	posts = '/posts/:year/:month/:day/:title/'

[params]
	author = "Joel Goguen"
	disableWebFonts = true
	since = 2013
	info = "Father, InfoSec, System Administrator, Software Developer"
	description = "This is the personal website for Joel Goguen"

	colorScheme = "auto"
	favicon_16 = "/img/favicon_16x16.png"
	favicon_32 = "/img/favicon_32x32.png"

	customSCSS = ["sass/style.scss"]

[[params.social]]
	name = "Github"
	icon = "fa fa-github fa-2x"
	weight = 1
	url = "https://github.com/jgoguen"
[[params.social]]
	name = "Mastodon"
	icon = "fa fa-mastodon fa-2x"
	weight = 2
	url = "https://infosec.exchange/@jgoguen"
[[params.social]]
	name = "Twitter"
	icon = "fa fa-twitter fa-2x"
	weight = 3
	url = "https://twitter.com/jgoguen"
[[params.social]]
	name = "LinkedIn"
	icon = "fa fa-linkedin fa-2x"
	weight = 50
	url = "https://www.linkedin.com/in/joelgoguen"
[[params.social]]
	name = "Buy Me A Coffee"
	icon = "fa fa-buymeacoffee fa-2x"
	weight = 97
	url = "https://www.buymeacoffee.com/jgoguen"
[[params.social]]
	name = "Liberapay"
	icon = "fa fa-liberapay fa-2x"
	weight = 98
	url = "https://liberapay.com/jgoguen"
[[params.social]]
	name = "PayPal"
	icon = "fa fa-paypal fa-2x"
	weight = 99
	url = "https://paypal.me/jtgoguen"

[taxonomies]
	tag = "tags"
	author = "authors"

[[menu.main]]
	name = "About Me"
	weight = 1
	url = "/about"

[[menu.main]]
	name = "Résumé"
	weight = 2
	url = "/docs/resume.pdf"

[[menu.main]]
	name = "Posts"
	weight = 3
	url = "/posts"

[[menu.main]]
	name = "Contact Me"
	weight = 4
	url = "/contact"
