{
 "title": "Unbound",
 "description": "Unbound DNS server queries and statistics",
 "tags": [
  "unbound",
  "openbsd",
  "influxdb"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "SHOW TAG VALUES FROM \"unbound_queries\" WITH KEY = \"host\""
    }
   },
   { "name": "forever", "query": "${VAR_FOREVER}" },
   {
    "name": "client",
    "query": {
     "query": "SHOW TAG VALUES FROM \"unbound_queries\" WITH KEY = \"client\""
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total queries",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "unbound_queries",
     "select": [
      [
       { "params": [ "response_size" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Blocked queries",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "unbound_adblock",
     "query": "SELECT count(\"client\") FROM \"unbound_adblock\" WHERE (\"host\" =~ /^$hostname$/ AND $timeFilter)",
     "select": [
      [
       { "params": [ "matched" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Percent Blocked",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$B / $A", "type": "math" }
   ]
  },
  {
   "title": "Failed/Rejected Queries",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_host",
     "measurement": "unbound_queries",
     "query": "SELECT count(\"response_size\") FROM \"unbound_queries\" WHERE (\"host\"::tag =~ /^$hostname$/ AND (\"return_code\"::tag = 'REFUSED' OR \"return_code\"::tag = 'SERVFAIL')) AND $timeFilter GROUP BY \"host\"::tag",
     "select": [
      [
       { "params": [ "response_size" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "return_code::tag", "operator": "=~", "value": "/^(REFUSED|SERVFAIL)$/" }
     ]
    }
   ]
  },
  { "title": "Cache Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Cache hit %",
   "type": "timeseries",
   "description": "Cache hit rate over the previous 5 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$B / $A", "type": "math" }
   ]
  },
  {
   "title": "Cache Prefetches /sec",
   "type": "timeseries",
   "description": "Cache prefetches per second over a 1 minute window",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" }
     ],
     "measurement": "unbound_stats",
     "query": "SELECT \"value\" FROM \"exec_value\" WHERE (\"type_instance\"::tag = 'total.num.prefetch') AND $timeFilter GROUP BY \"host\"::tag",
     "select": [
      [
       { "params": [ "prefetches" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Service Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Queries /sec",
   "type": "timeseries",
   "description": "DNS queries from clients per second over a 1 minute window ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    { "expression": "($A+$B+$C)/60", "reducer": "sum", "settings": { "mode": "replaceNN", "replaceWithValue": 0 }, "type": "math" }
   ]
  },
  {
   "title": "Mean Query Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" }
     ],
     "measurement": "unbound_queries",
     "select": [
      [
       { "params": [ "time_to_resolve" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "client::tag", "operator": "=~", "value": "/^$client$/" }
     ]
    }
   ]
  },
  {
   "title": "Median Query Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" }
     ],
     "measurement": "unbound_queries",
     "select": [
      [
       { "params": [ "time_to_resolve" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "client::tag", "operator": "=~", "value": "/^$client$/" }
     ]
    }
   ]
  },
  {
   "title": "Recursive Replies /sec",
   "type": "timeseries",
   "description": "Number of replies per second from upstream DNS servers over a 1 minute window",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" }
     ],
     "measurement": "unbound_stats",
     "select": [
      [
       { "params": [ "recursions" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Recursive Response Mean Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" }
     ],
     "measurement": "unbound_stats",
     "select": [
      [
       { "params": [ "recursion_mean" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Recursive Response Median Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" }
     ],
     "measurement": "unbound_stats",
     "select": [
      [
       { "params": [ "recursion_p50" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "DNS queries",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "alias": "Permitted DNS queries",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "unbound_queries",
     "query": "SELECT count(\"response_size\") FROM \"unbound_queries\" WHERE $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "response_size" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "client::tag", "operator": "=~", "value": "/^$client$/" }
     ]
    },
    {
     "alias": "Blocked DNS queries",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "unbound_adblock",
     "query": "SELECT count(\"matched\") FROM \"unbound_adblock\" WHERE $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "matched" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "client::tag", "operator": "=~", "value": "/^$client$/" }
     ]
    }
   ]
  },
  {
   "title": "Query Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top Queried Domains",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "limit": "100",
     "measurement": "unbound_queries",
     "select": [
      [
       { "params": [ "response_size" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "return_code::tag", "operator": "=", "value": "NOERROR" },
      { "condition": "AND", "key": "name::tag", "operator": "!~", "value": "/^(.+\\.)?example\\.\\w+$/" },
      { "condition": "AND", "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name::tag", "operator": "!~", "value": "/.+\\.arpa\\.$/" },
      { "condition": "AND", "key": "name::tag", "operator": "!~", "value": "/^example\\.[a-z]+\\.$/" },
      {
       "condition": "AND",
       "key": "name::tag",
       "operator": "!~",
       "value": "/^(www\\.)?googleapis\\.com\\.$/"
      },
      { "condition": "AND", "key": "name::tag", "operator": "!=", "value": "spectrum.s3.amazonaws.com." },
      { "condition": "AND", "key": "name::tag", "operator": "!=", "value": "connect.samsungiotcloud.com." },
      { "condition": "AND", "key": "client::tag", "operator": "=~", "value": "/^$client$/" },
      { "condition": "AND", "key": "name::tag", "operator": "!=", "value": "api.cloudflare.com." },
      { "condition": "AND", "key": "name::tag", "operator": "!=", "value": "arstechnica.com." },
      { "condition": "AND", "key": "name::tag", "operator": "!=", "value": "unifi.jgoguen.ca." }
     ]
    }
   ]
  },
  {
   "title": "Top Blocked Domains",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "limit": "100",
     "measurement": "unbound_queries",
     "select": [
      [
       { "params": [ "response_size" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "return_code::tag", "operator": "=", "value": "NXDOMAIN" },
      {
       "condition": "AND",
       "key": "name::tag",
       "operator": "!~",
       "value": "/^.+?\\.(com|org|net|ca|local)\\.jgoguen\\.ca\\.$/"
      },
      { "condition": "AND", "key": "name::tag", "operator": "!~", "value": "/^(.+\\.)?example\\.\\w+$/" },
      { "condition": "AND", "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" },
      {
       "condition": "AND",
       "key": "name::tag",
       "operator": "!~",
       "value": "/^minor\\-api\\-os\\.hoyoverse\\.com\\.$/"
      },
      { "condition": "AND", "key": "name::tag", "operator": "!~", "value": "/.+\\.arpa\\.$/" },
      { "condition": "AND", "key": "name::tag", "operator": "!~", "value": "/^doh\\.test\\.$/" },
      { "condition": "AND", "key": "client::tag", "operator": "=~", "value": "/^$client$/" }
     ]
    }
   ]
  },
  {
   "title": "Query Types",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "type::tag" ], "type": "tag" }
     ],
     "measurement": "unbound_queries",
     "select": [
      [
       { "params": [ "response_size" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "client::tag", "operator": "=~", "value": "/^$client$/" }
     ]
    }
   ]
  },
  {
   "title": "Reply Code",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "return_code::tag" ], "type": "tag" }
     ],
     "measurement": "unbound_queries",
     "select": [
      [
       { "params": [ "response_size" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "client::tag", "operator": "=~", "value": "/^$client$/" }
     ]
    }
   ]
  },
  {
   "title": "Query Log",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Recent Allowed Queries",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "return_code" ], "type": "tag" },
      { "params": [ "client::tag" ], "type": "tag" }
     ],
     "limit": "100",
     "measurement": "unbound_queries",
     "select": [
      [
       { "params": [ "time_to_resolve" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "return_code::tag", "operator": "=", "value": "NOERROR" },
      { "condition": "AND", "key": "client::tag", "operator": "=~", "value": "/^$client$/" }
     ]
    }
   ]
  },
  {
   "title": "Recent Blocked Queries",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "client::tag" ], "type": "tag" }
     ],
     "limit": "100",
     "measurement": "unbound_queries",
     "select": [
      [
       { "params": [ "time_to_resolve" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "return_code::tag", "operator": "=", "value": "NXDOMAIN" },
      { "condition": "AND", "key": "client::tag", "operator": "=~", "value": "/^$client$/" }
     ]
    }
   ]
  },
  {
   "title": "Top Clients",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "clientip::tag" ], "type": "tag" },
      { "params": [ "client::tag" ], "type": "tag" }
     ],
     "measurement": "unbound_queries",
     "select": [
      [
       { "params": [ "response_size" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "client::tag", "operator": "=~", "value": "/^$client$/" }
     ]
    }
   ]
  },
  {
   "title": "Recent Failed Queries",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "client::tag" ], "type": "tag" },
      { "params": [ "host::tag" ], "type": "tag" }
     ],
     "limit": "100",
     "measurement": "unbound_queries",
     "select": [
      [
       { "params": [ "time_to_resolve" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "return_code::tag", "operator": "=", "value": "SERVFAIL" },
      { "condition": "AND", "key": "client::tag", "operator": "=~", "value": "/^$client$/" }
     ]
    }
   ]
  },
  { "title": "Slow Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Recent Slow Queries (>1s)",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 75 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "return_code" ], "type": "tag" },
      { "params": [ "client::tag" ], "type": "tag" }
     ],
     "limit": "100",
     "measurement": "unbound_queries",
     "select": [
      [
       { "params": [ "time_to_resolve" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "return_code::tag", "operator": "=", "value": "NOERROR" },
      { "condition": "AND", "key": "client::tag", "operator": "=~", "value": "/^$client$/" }
     ]
    }
   ]
  },
  {
   "title": "Recent Slow Queries (>2s)",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 75 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "return_code" ], "type": "tag" },
      { "params": [ "client::tag" ], "type": "tag" }
     ],
     "limit": "100",
     "measurement": "unbound_queries",
     "select": [
      [
       { "params": [ "time_to_resolve" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "return_code::tag", "operator": "=", "value": "NOERROR" },
      { "condition": "AND", "key": "client::tag", "operator": "=~", "value": "/^$client$/" }
     ]
    }
   ]
  },
  {
   "title": "Recent Slow Queries (>5s)",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 86 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "return_code" ], "type": "tag" },
      { "params": [ "client::tag" ], "type": "tag" }
     ],
     "limit": "100",
     "measurement": "unbound_queries",
     "select": [
      [
       { "params": [ "time_to_resolve" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "return_code::tag", "operator": "=", "value": "NOERROR" },
      { "condition": "AND", "key": "client::tag", "operator": "=~", "value": "/^$client$/" }
     ]
    }
   ]
  }
 ]
}