{
 "title": "Unbound",
 "description": "Unbound with AD block usage",
 "tags": [
  "unbound",
  "openbsd",
  "influxdb",
  "collectd"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Hostname",
    "query": "SHOW TAG VALUES FROM \"unbound_queries\" WITH KEY = \"host\""
   },
   { "name": "forever", "query": "${VAR_FOREVER}" },
   { "name": "pct", "label": "Percentile", "query": "25,50,75,90,95,99" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total queries",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "unbound_queries",
     "select": [
      [
       { "params": [ "response_size" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Blocked queries",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "unbound_adblock",
     "query": "SELECT count(\"client\") FROM \"unbound_adblock\" WHERE (\"host\" =~ /^$hostname$/ AND $timeFilter)",
     "select": [
      [
       { "params": [ "matched" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Percent Blocked",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$forever" ], "type": "time" }
     ],
     "measurement": "unbound_queries",
     "query": "SELECT count(\"time_to_resolve\") FROM \"unbound_queries\" WHERE (\"host\" =~ /^$hostname$/ AND $timeFilter) fill(null)",
     "select": [
      [
       { "params": [ "response_size" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$forever" ], "type": "time" }
     ],
     "measurement": "unbound_adblock",
     "query": "SELECT count(\"client\") FROM \"unbound_adblock\" WHERE (\"host\" =~ /^$hostname$/ AND $timeFilter) fill(null)",
     "select": [
      [
       { "params": [ "matched" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Domains on blocklist",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "exec_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instance", "operator": "=", "value": "unbound" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "num.adhosts" },
      { "condition": "AND", "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  { "title": "Cache Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Memory Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" }
     ],
     "measurement": "exec_value",
     "query": "SELECT sum(\"value\") FROM \"exec_value\" WHERE (\"instance\" = 'unbound' AND \"type_instance\" =~ /^mem.cache.*/) AND $timeFilter GROUP BY time(5m), \"host\"::tag",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instance", "operator": "=", "value": "unbound" },
      { "condition": "AND", "key": "type_instance", "operator": "=~", "value": "/^mem.cache.*/" },
      { "condition": "AND", "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Cache hit %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$B / $A", "type": "math" }
   ]
  },
  {
   "title": "Cached Messages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" }
     ],
     "measurement": "exec_value",
     "query": "SELECT sum(\"value\") FROM \"exec_value\" WHERE (\"instance\" = 'unbound' AND \"type_instance\" = 'msg.cache.count') AND $timeFilter GROUP BY time(5m), \"host\"::tag",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instance", "operator": "=", "value": "unbound" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "mem.cache.message" },
      { "condition": "AND", "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Cache Prefetches /sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" }
     ],
     "measurement": "exec_value",
     "query": "SELECT \"value\" FROM \"exec_value\" WHERE (\"type_instance\"::tag = 'total.num.prefetch') AND $timeFilter GROUP BY \"host\"::tag",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "type_instance::tag", "operator": "=", "value": "total.num.prefetch" },
      { "condition": "AND", "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Service Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" }
     ],
     "measurement": "exec_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instance", "operator": "=", "value": "unbound" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "time.up" },
      { "condition": "AND", "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Queries / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" }
     ],
     "measurement": "unbound_queries",
     "query": "SELECT non_negative_derivative(last(\"value\"), 1s) FROM \"exec_value\" WHERE (\"instance\" = 'unbound' AND \"type_instance\" = 'total.num.queries') AND $timeFilter GROUP BY time(1s), \"host\"::tag",
     "select": [
      [
       { "params": [ "response_size" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Secure Responses %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$A / $D", "type": "math" }
   ]
  },
  {
   "title": "p$pct Query Response Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "unbound_queries",
     "select": [
      [
       { "params": [ "time_to_resolve" ], "type": "field" },
       { "params": [ "$pct" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "p$pct Recursive Response Mean Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "type_instance::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exec_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "$pct" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "instance::tag", "operator": "=", "value": "unbound" },
      { "condition": "AND", "key": "type_instance::tag", "operator": "=", "value": "total.recursion.time.avg" }
     ]
    }
   ]
  },
  {
   "title": "p$pct Recursive Response Median Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "type_instance::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "exec_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "$pct" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "instance::tag", "operator": "=", "value": "unbound" },
      { "condition": "AND", "key": "type_instance::tag", "operator": "=", "value": "total.recursion.time.median" }
     ]
    }
   ]
  },
  {
   "title": "Queries Failing ACLs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 20 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" }
     ],
     "measurement": "exec_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "instance::tag", "operator": "=", "value": "unbound" },
      { "condition": "AND", "key": "type_instance::tag", "operator": "=", "value": "unwanted.queries" }
     ]
    }
   ]
  },
  {
   "title": "Unsolicited Replies",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 20 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" }
     ],
     "measurement": "exec_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "instance::tag", "operator": "=", "value": "unbound" },
      { "condition": "AND", "key": "type_instance::tag", "operator": "=", "value": "unwanted.replies" }
     ]
    }
   ]
  },
  {
   "title": "Query Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "DNS queries",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "alias": "Permitted DNS queries",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "unbound_queries",
     "query": "SELECT count(\"response_size\") FROM \"unbound_queries\" WHERE $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "response_size" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "Blocked DNS queries",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "unbound_adblock",
     "query": "SELECT count(\"matched\") FROM \"unbound_adblock\" WHERE $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "matched" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Top Queried Domains",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "limit": "100",
     "measurement": "unbound_queries",
     "select": [
      [
       { "params": [ "response_size" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "return_code::tag", "operator": "=", "value": "NOERROR" },
      { "condition": "AND", "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Top Blocked Domains",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "limit": "100",
     "measurement": "unbound_queries",
     "select": [
      [
       { "params": [ "response_size" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "return_code::tag", "operator": "=", "value": "NXDOMAIN" },
      { "condition": "AND", "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Query Types",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "type::tag" ], "type": "tag" }
     ],
     "measurement": "unbound_queries",
     "select": [
      [
       { "params": [ "response_size" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Reply Code",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "return_code::tag" ], "type": "tag" }
     ],
     "measurement": "unbound_queries",
     "select": [
      [
       { "params": [ "response_size" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Query Log",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Recent Queries",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "return_code" ], "type": "tag" },
      { "params": [ "client::tag" ], "type": "tag" }
     ],
     "limit": "100",
     "measurement": "unbound_queries",
     "select": [
      [
       { "params": [ "time_to_resolve" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Top Clients",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "clientip::tag" ], "type": "tag" },
      { "params": [ "client::tag" ], "type": "tag" }
     ],
     "measurement": "unbound_queries",
     "select": [
      [
       { "params": [ "response_size" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  }
 ]
}